name: CCagrapoc
run-name: Setting up the MSSQL Database deployment from repository
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Test Output
        run: echo "Here is the output of the test job"
  Connect-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show Database
        run: sqlcmd -S ${{secrets.DB_HOSTNAME}},1433 -U ${{secrets.DB_USERNAME}} -P ${{secrets.DB_PASSWORD}} -Q "SELECT name FROM sys.databases;"
