name: CCagrapoc
run-name: Setting up the MSSQL Database deployment from repository
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Install sqlcmd
         run: |
            sudo apt-get update
            sudo apt-get install -y mssql-tools
            echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
            source ~/.bashrc

       - name: Run sqlcmd command
         run: |
            sqlcmd -S ${{secrets.DB_HOSTNAME}},1433 -U ${{secrets.DB_USERNAME}} -P ${{secrets.DB_PASSWORD}} -Q "SELECT name FROM sys.databases;"
